/* ============================================================
   services.js — single source of data for the Services mega-menu
   (layout.js) AND the Service Detail page
   (zyanix-service-detail-page.html?service=<slug>).
   Add a service here and it appears in the menu + gets its own
   detail page automatically.
   ============================================================ */
(function(){
  var ICON = {
    code:'<polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/>',
    phone:'<rect x="5" y="2" width="14" height="20" rx="2"/><line x1="12" y1="18" x2="12.01" y2="18"/>',
    cloud:'<path d="M18 10h-1.26A8 8 0 1 0 9 20h9a5 5 0 0 0 0-10z"/>',
    pen:'<path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.12 2.12 0 0 1 3 3L12 15l-4 1 1-4z"/>',
    shield:'<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>',
    support:'<path d="M3 18v-6a9 9 0 0 1 18 0v6"/><path d="M21 19a2 2 0 0 1-2 2h-1a2 2 0 0 1-2-2v-3a2 2 0 0 1 2-2h3zM3 19a2 2 0 0 0 2 2h1a2 2 0 0 0 2-2v-3a2 2 0 0 0-2-2H3z"/>',
    cart:'<circle cx="9" cy="21" r="1"/><circle cx="20" cy="21" r="1"/><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"/>',
    link:'<path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"/><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"/>',
    rocket:'<path d="M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09z"/><path d="M12 15l-3-3a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.35 22.35 0 0 1-4 2z"/>',
    layers:'<polygon points="12 2 2 7 12 12 22 7 12 2"/><polyline points="2 17 12 22 22 17"/><polyline points="2 12 12 17 22 12"/>',
    cpu:'<rect x="4" y="4" width="16" height="16" rx="2"/><rect x="9" y="9" width="6" height="6"/><path d="M9 1v3M15 1v3M9 20v3M15 20v3M1 9h3M1 15h3M20 9h3M20 15h3"/>',
    building:'<rect x="4" y="2" width="16" height="20" rx="1"/><path d="M9 22v-4h6v4M8 6h.01M12 6h.01M16 6h.01M8 10h.01M12 10h.01M16 10h.01M8 14h.01M12 14h.01M16 14h.01"/>',
    globe:'<circle cx="12" cy="12" r="10"/><line x1="2" y1="12" x2="22" y2="12"/><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"/>'
  };

  function S(slug,name,icon,group,tagline,overview,features,tech,benefits){
    return {slug:slug,name:name,icon:ICON[icon],group:group,tagline:tagline,overview:overview,features:features,tech:tech,benefits:benefits};
  }

  window.ZYANIX_SERVICE_GROUPS = ['Build','Design & Operate','Specialized'];

  window.ZYANIX_SERVICES = [
    S('web-development','Web Development','code','Build',
      'Fast, secure and scalable websites and web apps.',
      'We build modern websites, portals and web applications that load quickly, rank well and scale as your traffic grows. From marketing sites to complex dashboards, every build is responsive, accessible and easy for your team to maintain.',
      ['Responsive, mobile-first front-ends','Custom CMS and admin panels','Server-side rendering and SEO-ready markup','Secure authentication and role-based access','Performance tuning (Core Web Vitals)','Analytics, tracking and A/B-test hooks'],
      ['React','Next.js','Node.js','TypeScript','PostgreSQL','AWS'],
      [['Faster pages','Optimised builds that keep bounce rates low.'],['Built to scale','Architecture ready for 10x traffic.'],['Easy to manage','Clean code and docs your team can own.']]),
    S('mobile-app-development','Mobile App Development','phone','Build',
      'iOS and Android apps people enjoy using.',
      'We design and build native-feeling mobile apps for iOS and Android from a single codebase where it makes sense, and fully native where performance demands it. You get store-ready apps with analytics, push notifications and offline support.',
      ['iOS and Android from one codebase','Push notifications and deep links','Offline mode and background sync','Payments, maps and device integrations','App Store / Play Store release support','Crash reporting and in-app analytics'],
      ['React Native','Flutter','Swift','Kotlin','Firebase','GraphQL'],
      [['One team, two platforms','Shared code cuts cost and time to market.'],['Native feel','Smooth animations and platform conventions.'],['Release-ready','We handle store submission and updates.']]),
    S('custom-software-development','Custom Software Development','layers','Build',
      'Software shaped around the way your business works.',
      'Off-the-shelf tools rarely fit perfectly. We build custom software — internal tools, workflow automation and full platforms — that matches your processes instead of forcing you to change them.',
      ['Requirement workshops and technical discovery','Modular, API-first architecture','Workflow automation and reporting','Third-party and legacy system integration','Automated testing and CI/CD','Long-term maintenance plans'],
      ['Node.js','Python','.NET','PostgreSQL','Docker','Redis'],
      [['Perfect fit','Features you need, nothing you do not.'],['Own your stack','No licence lock-in or per-seat surprises.'],['Future-proof','Modular design that grows with you.']]),
    S('ecommerce-development','E-commerce Development','cart','Build',
      'Online stores that convert browsers into buyers.',
      'We build high-converting storefronts and marketplaces with fast checkout, inventory sync and payment integrations. Whether you are launching a single store or a multi-vendor marketplace, we make it easy to sell and easy to scale.',
      ['Custom storefronts and multi-vendor marketplaces','Secure checkout and payment gateways','Inventory, order and shipping management','Discounts, subscriptions and loyalty tools','Search, filters and recommendations','ERP / CRM / accounting integrations'],
      ['Shopify','Next.js','Stripe','Razorpay','Node.js','Algolia'],
      [['Higher conversion','Frictionless checkout and fast pages.'],['Operational control','Orders and stock in one dashboard.'],['Omnichannel ready','Sell on web, mobile and marketplaces.']]),
    S('progressive-web-apps','Progressive Web Apps','globe','Build',
      'App-like experiences straight from the browser.',
      'Progressive Web Apps give users installable, offline-capable experiences without an app-store download. They are a cost-effective way to reach every device with one codebase.',
      ['Installable on home screen','Offline support via service workers','Push notifications on supported devices','Lightning-fast repeat loads','Single codebase for all devices','Lighthouse-audited performance'],
      ['React','Workbox','Vite','IndexedDB','Web Push','Node.js'],
      [['No app-store friction','Users install in one tap.'],['Lower cost','One build covers web and mobile.'],['Works offline','Keeps users productive anywhere.']]),
    S('ui-ux-design','UI/UX Design','pen','Design & Operate',
      'Beautiful, usable experiences backed by research.',
      'Great products start with understanding users. Our designers run research, map journeys, prototype quickly and ship polished interfaces and design systems your developers can implement without guesswork.',
      ['User research and journey mapping','Wireframes and clickable prototypes','Visual design and brand alignment','Design systems and component libraries','Usability testing and iteration','Accessibility (WCAG) reviews'],
      ['Figma','Storybook','Lottie','Maze','Hotjar','Tailwind'],
      [['Higher engagement','Clear flows users complete.'],['Faster delivery','Design systems speed up development.'],['Inclusive','Accessible for every user.']]),
    S('cloud-devops','Cloud & DevOps','cloud','Design & Operate',
      'Reliable, secure and cost-efficient infrastructure.',
      'We design cloud architectures, automate deployments and set up monitoring so your product stays fast and available. Our DevOps practices shorten release cycles while keeping costs under control.',
      ['AWS, Azure and GCP architecture','Infrastructure as code (Terraform)','CI/CD pipelines and automated testing','Containers and Kubernetes','Monitoring, logging and alerting','Cost optimisation and security hardening'],
      ['AWS','Docker','Kubernetes','Terraform','GitHub Actions','Grafana'],
      [['Ship faster','Automated pipelines deploy in minutes.'],['Stay online','Resilient, auto-scaling infrastructure.'],['Spend less','Right-sized resources and usage alerts.']]),
    S('digital-transformation','Digital Transformation','shield','Design & Operate',
      'Modernise processes and unlock efficiency with technology.',
      'We help organisations move from paper, spreadsheets and disconnected tools to streamlined digital operations. We assess your current state, design a roadmap and deliver it in measurable phases.',
      ['Process audit and digital roadmap','Legacy system modernisation','Workflow and document automation','Data consolidation and dashboards','Change management and training','Phased delivery with clear KPIs'],
      ['Power Platform','Python','Node.js','PostgreSQL','Metabase','Zapier'],
      [['Less manual work','Automation frees your team for higher-value tasks.'],['Single source of truth','Connected data and real-time reports.'],['Measurable ROI','Every phase tied to KPIs.']]),
    S('it-support-maintenance','IT Support & Maintenance','support','Design & Operate',
      'Keep your systems running smoothly, always.',
      'Launching is just the beginning. Our support plans cover bug fixes, security patches, upgrades and performance monitoring so your product stays healthy and your team stays focused on growth.',
      ['24/7 monitoring and incident response','Security patches and dependency updates','Bug fixing with SLA-backed response times','Backups and disaster-recovery drills','Performance audits and optimisation','Monthly reports and roadmap reviews'],
      ['Datadog','Sentry','AWS','Linux','PagerDuty','GitHub'],
      [['Peace of mind','Problems fixed before users notice.'],['Predictable cost','Fixed monthly plans.'],['Always current','Stay on supported, secure versions.']]),
    S('api-integration','API Integration','link','Design & Operate',
      'Connect your tools so data flows without manual effort.',
      'We connect your apps, payment providers, CRMs, ERPs and third-party services through reliable, well-documented APIs — and build custom APIs when you need to expose your own data securely.',
      ['REST and GraphQL API design','Payment, CRM, ERP and logistics integrations','Webhooks and event-driven workflows','API gateways, rate limiting and auth','Data mapping and synchronisation','Interactive documentation (OpenAPI)'],
      ['REST','GraphQL','OpenAPI','Kafka','Node.js','Postman'],
      [['No more copy-paste','Systems stay in sync automatically.'],['Secure by design','Authentication and rate limits built in.'],['Easy to extend','Clean contracts for future integrations.']]),
    S('mvp-development','MVP Development','rocket','Specialized',
      'Validate your idea fast with a focused first version.',
      'We help founders ship a minimum viable product in weeks, not months. We prioritise the features that prove your idea, build them well and leave a codebase that can grow into the full product.',
      ['Idea validation and scope workshops','Prioritised feature roadmap','Rapid prototyping and 6–10 week builds','Analytics to measure early traction','Investor-ready demos','Smooth path from MVP to v1'],
      ['Next.js','React Native','Supabase','Firebase','Stripe','Vercel'],
      [['Launch quickly','Get real user feedback early.'],['Control the budget','Build only what proves the idea.'],['Room to grow','Architecture that scales past the MVP.']]),
    S('saas-product-development','SaaS Product Development','layers','Specialized',
      'Multi-tenant platforms built for recurring revenue.',
      'We build SaaS products end to end: multi-tenant architecture, subscription billing, admin tooling and analytics. Our teams have launched SaaS platforms across fintech, healthcare and logistics.',
      ['Multi-tenant architecture','Subscription billing and invoicing','Role-based access and SSO','Usage analytics and admin dashboards','Public APIs and webhooks','Scalable, secure cloud deployment'],
      ['Next.js','Node.js','PostgreSQL','Stripe Billing','AWS','Redis'],
      [['Recurring revenue ready','Billing and plans from day one.'],['Secure tenancy','Strict data isolation per customer.'],['Built to scale','Handles growth without rewrites.']]),
    S('ai-ml-integration','AI/ML Integration','cpu','Specialized',
      'Add practical intelligence to your product.',
      'We integrate AI where it creates real value — search, recommendations, document processing, chat assistants and forecasting — with proper evaluation, guardrails and monitoring so results are reliable.',
      ['LLM-powered assistants and workflows','Recommendation and personalisation','Document and image processing','Forecasting and anomaly detection','Data pipelines and model evaluation','Privacy, safety and cost controls'],
      ['Python','OpenAI / Anthropic APIs','LangChain','TensorFlow','Pinecone','FastAPI'],
      [['Real use cases','Focused on measurable business value.'],['Reliable output','Evaluation and guardrails built in.'],['Cost-aware','Usage monitoring and optimisation.']]),
    S('startup-product-development','Startup Product Development','rocket','Specialized',
      'A flexible product team for early-stage companies.',
      'We act as your extended product and engineering team — from idea and design to launch and iteration — with flexible engagement models that fit startup budgets and fast-changing priorities.',
      ['Product strategy and roadmap support','Design + engineering in one team','Weekly demos and transparent progress','Flexible, scalable team size','Investor-ready technical documentation','Post-launch growth support'],
      ['React','Node.js','Flutter','Firebase','AWS','Figma'],
      [['Move fast','Weekly releases and quick pivots.'],['Startup-friendly','Flexible engagement and pricing.'],['Full-stack partner','Design, build and launch under one roof.']]),
    S('enterprise-solutions','Enterprise Solutions','building','Specialized',
      'Secure, compliant systems for large organisations.',
      'We deliver enterprise-grade platforms with the security, compliance and integration depth large organisations require — from internal portals and ERP extensions to data platforms and modernisation programmes.',
      ['Enterprise architecture and governance','SSO, audit trails and compliance support','ERP / CRM / legacy integrations','High-availability, multi-region deployments','Data warehousing and BI','Dedicated teams and SLAs'],
      ['Java','.NET','Azure','Kafka','Oracle','Kubernetes'],
      [['Compliance-ready','Security and audit built into every layer.'],['Integrates everywhere','Works with your existing landscape.'],['Dedicated support','Named teams with clear SLAs.']])
  ];
})();
